Resources:
  BankTellerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      RoleName: "BankTellerLambdaRole-${self:provider.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "BankTellerLambdaPolicy-${self:provider.stage}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Get*
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource:
                  - "Fn::Join":
                      - ":"
                      - - "arn:aws:dynamodb"
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - "table/ReceiptBankDBTable"
      Tags:
        - Key: "AppName"
          Value: "receipt-bank-db"
